name: MenuPlugin
main: com.menuplugin.Main
version: 1.0
api-version: 1.13
commands:
  pmenu:
    description: Open menu
    usage: /pmenu
  spawn:
    description: teleport player to spawn
    usage: /spawn